version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/glass-bottle
permissions:
  - object: /home/ec2-user/glass-bottle
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 120
      runas: root
